version: '3'

volumes:
  auth_postgres_volume:
  auth_redis_volume:

services:
  auth_pg:
    image: postgres:14-alpine3.17
    container_name: auth_pg
    env_file:
      - local.env
    ports:
      - "54321:5432"
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data
    networks:
      - auth

  auth_redis:
    image: redis:7.2.5-alpine3.20
    container_name: auth_redis
    env_file:
      - local.env
    ports:
      - "6379:6379"
    volumes:
      - auth_redis_volume:/data
    networks:
      - auth

  auth_migrator:
    container_name: auth_migrator
    image: auth_migrator
    build:
      context: .
      dockerfile: migrator/migrator-local.Dockerfile
    env_file:
      - local.env
    restart: on-failure
    networks:
      - auth

networks:
  auth:
    external: true